#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | mirror-operators.yml' 
  hosts: localhost 
  become: yes
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "bundle-operators"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"

  tasks:
    - name: Create operator bundle
      import_role:
        name: mirror-operator 
        tasks_from: mirror-operators.yml
