---
roles:
  - src: https://github.com/cadjai/mirror-ocp4-contents-for-artifactory.git 
    scm: git
    name: mirror-ocp4-content-artifactory 

#collections:
  #- name: https://github.com/nginxinc/ansible-collection-nginx.git
  #- name: nginxinc.nginx_core 
  #  type: git
    #version: 0.1.1
